#!/usr/bin/env bash
CRITERION="04-io-expressiveness"
echo "[$CRITERION]"
echo ""
echo "Plain text:  both handle it"
echo "JSON:        LiveFoldersFS now enforces structural schema (required fields, property types)"
echo "             before handler runs; MCP enforces typed schema at protocol layer."
echo "Multiline:   LiveFoldersFS native (stdin); MCP requires escaped string parameter"
echo "Binary:      LiveFoldersFS: pipe binary to handler; MCP: base64 encode in string (workaround)"
echo "Constraints: LiveFoldersFS: min/max length, regex pattern for strings; MCP: type/required only"
echo ""
echo "  Example: json_reflect with schema {required:[text], properties:{text:{type:string}}}"
echo "    Valid input   {\"text\":\"hello\"} → passes, handler runs"
echo "    Missing field {}               → [ERROR:INVALID_INPUT] missing required field: 'text'"
echo "    Wrong type    {\"text\":42}      → [ERROR:INVALID_INPUT] field 'text' expected type 'string'"
echo ""
echo "  Winner: MCP for protocol-enforced schema; LiveFoldersFS now competitive with"
echo "    opt-in structural validation (required fields, property types, string constraints)."
