#!/usr/bin/env bash
CRITERION="05-security"
echo "[$CRITERION]"
echo "  Both: run as user process, no OS sandboxing"
echo ""
echo "  LiveFoldersFS (v0.7.0):"
echo "    - Opt-in per-endpoint structural validation via folder.yaml input.schema"
echo "    - Supports: required fields, property type checks, string min/max/pattern"
echo "    - Malformed input rejected before handler runs → no shell code executed"
echo "    - Remaining gap: opt-in (author must declare schema), not protocol-enforced"
echo "    - Shell injection within handler body is still the author's responsibility"
echo ""
echo "  MCP:"
echo "    - Schema validation enforced unconditionally at protocol layer"
echo "    - Every tool rejects mistyped inputs automatically"
echo "    - No equivalent of string pattern or length constraints without custom validation"
echo ""
echo "  Example (LiveFoldersFS search endpoint, schema: required=[query], query:string):"
echo "    Valid:   echo '{\"query\":\"cats\"}' → handler runs, returns result"
echo "    Missing: echo '{}'               → [ERROR:INVALID_INPUT] missing required field: 'query'"
echo "    Wrong:   echo '{\"query\":42}'     → [ERROR:INVALID_INPUT] field 'query' expected type 'string'"
echo ""
echo "  Winner: MCP for unconditional protocol-layer enforcement;"
echo "    LiveFoldersFS ~ (partial, improved) — structural validation now available opt-in."
